# Generated by Django 5.1.4 on 2025-01-04 13:24

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madrid', '0003_userprofile_age_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='contact_info',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KG'),
        ),
    ]
