# Generated by Django 5.1.4 on 2025-01-06 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madrid', '0006_courierreview_storereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('клиент', 'клиент'), ('курьер', 'курьер'), ('владелец', 'владелец'), ('aдминистратор', 'администратор')], default='клиент', max_length=16),
        ),
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_image', models.ImageField(blank=True, null=True, upload_to='store_image/')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madrid.store')),
            ],
        ),
    ]
